//  Saga
export const FETCH_FILMS = "FETCH_FILMS";
export const FETCH_FILM = "FETCH_FILM";

//  Reducer
export const FETCH_FILMS_SUCCESS = "FETCH_FILMS_SUCCESS";
export const FETCH_FILM_SUCCESS = "FETCH_FILM_SUCCESS";


// Saga
export const REGISTER_USER = "REGISTER_USER";
export const VALIDATE_USER = "VALIDATE_USER";

// Reducer
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const VALIDATE_USER_SUCCESS = "VALIDATE_USER_SUCCESS";